Repository boostcampaitech3/final-project-level3-recsys-10, pull requests merged in 2022-06, with the labels that each got.

#67 [model/#29] Implicit Autorec Code Add
  EDA/beeradvocate_EDA_styoo.ipynb
  EDA/ratebeer_EDA_gyeongtae.ipynb
  data_engineering/data_preprocessing.ipynb
  model/autorec_experiment.ipynb
  model/autorec_experiment_bce.ipynb
  model/autorec_experiment_rmse.ipynb
  model/autorec_experiment_rmse_normalize.ipynb
  model/autorec_implicit_korean.ipynb
  model/autorec_implicit_korean_test.ipynb
Labels: 🐥 experiment, 🙏 model, ⚡ test

#68 [feat/#37] Product Serving 완료
  .github/workflows/docker-publish.yml
  Dockerfile
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: ✨ feat

#72 [serving] CI/CD 완료!
  .github/workflows/docker-publish.yml
  Dockerfile
  EDA/beeradvocate_EDA_styoo.ipynb
  EDA/ratebeer_EDA_gyeongtae.ipynb
  README.md
  data_engineering/data_preprocessing.ipynb
  model/autorec_experiment.ipynb
  model/autorec_experiment_bce.ipynb
  model/autorec_experiment_rmse.ipynb
  model/autorec_experiment_rmse_normalize.ipynb
  model/autorec_implicit_korean.ipynb
  model/autorec_implicit_korean_test.ipynb
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: 👩‍🍳 serving

#73 [test] CI/CD 테스트 중입니다.
  frontend/templates/index.html
Labels: ⚡ test

#74 [serving] start.sh 추가
  frontend/templates/beerList.html
  start.sh
Labels: 👩‍🍳 serving

#75 [Refactor/#69] model ipynb code 이동
  backend/recommendAPI/autorec.ipynb
  backend/recommendAPI/autorec/autorec.ipynb
  backend/recommendAPI/autorec/autorec_crawling.ipynb
  backend/recommendAPI/autorec/autorec_experiment_bce.ipynb
  backend/recommendAPI/autorec/autorec_experiment_rmse.ipynb
  backend/recommendAPI/autorec/autorec_experiment_rmse_normalize.ipynb
  backend/recommendAPI/autorec/autorec_experiment_web_inference.ipynb
  backend/recommendAPI/autorec/autorec_implicit_korean.ipynb
  backend/recommendAPI/autorec/autorec_implicit_korean_test.ipynb
  backend/recommendAPI/autorec_crawling.ipynb
  backend/recommendAPI/model.py
  backend/recommendAPI/popular/popular.ipynb
  model/autorec_implicit_korean_test.ipynb
Labels: 🔨 refactor
